apiVersion: v2
name: load-balancer-operator
description: A Helm chart to deploy the Infratographer load-balancer-operator 
type: application
version: 0.0.1
appVersion: "0.0.1"
kubeVersion: ">=1.24"

dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.13.3
  - name: reloader
    condition: reloader.enabled
    version: "1.2.1"
    repository: "https://stakater.github.io/stakater-charts"
